"""The enclave-mcp entry point refuses an incompatible MCP SDK with one clear line."""

import os
import subprocess
import sys
from pathlib import Path

import pytest

import advanced_vault
import advanced_vault.mcp_server as mcp_server

PROJECT_ROOT = Path(advanced_vault.__file__).resolve().parent.parent
FIX = 'pip install "mcp>=1.0.0,<2"'


def _fake_mcp_dist(tmp_path: Path, version: str) -> Path:
    """A sys.path entry whose metadata claims mcp==version (shadows the real one)."""
    site = tmp_path / "fake-site"
    info = site / f"mcp-{version}.dist-info"
    info.mkdir(parents=True)
    (info / "METADATA").write_text(f"Metadata-Version: 2.1\nName: mcp\nVersion: {version}\n")
    return site


@pytest.mark.parametrize("version", ["1.0.0", "1.30.0", "1.99.1"])
def test_mcp_1x_is_accepted(monkeypatch, version):
    monkeypatch.setattr(mcp_server, "_mcp_sdk_version", lambda: version)
    assert mcp_server.mcp_sdk_problem() is None


@pytest.mark.parametrize("version", ["2.0.0", "2.2.0", "2.0.0rc1", "3.1"])
def test_mcp_2_or_later_is_rejected(monkeypatch, version):
    monkeypatch.setattr(mcp_server, "_mcp_sdk_version", lambda: version)
    problem = mcp_server.mcp_sdk_problem()
    assert problem and version in problem


def test_missing_mcp_is_reported(monkeypatch):
    monkeypatch.setattr(mcp_server, "_mcp_sdk_version", lambda: None)
    monkeypatch.setattr(mcp_server.util, "find_spec", lambda name: None)
    assert "not installed" in mcp_server.mcp_sdk_problem()


def test_main_exits_with_one_line_fix_on_mcp_2(monkeypatch):
    monkeypatch.setattr(mcp_server, "_mcp_sdk_version", lambda: "2.2.0")

    with pytest.raises(SystemExit) as excinfo:
        mcp_server.main()

    message = excinfo.value.code  # a str code: printed to stderr, exit status 1
    assert isinstance(message, str)
    assert "\n" not in message
    assert "mcp 2.2.0" in message
    assert FIX in message


def _run_with_fake_mcp(tmp_path: Path, version: str, *args: str) -> subprocess.CompletedProcess:
    env = dict(os.environ)
    env["PYTHONPATH"] = os.pathsep.join([str(_fake_mcp_dist(tmp_path, version)), str(PROJECT_ROOT)])
    env["VAULT_PATH"] = str(tmp_path / "vault")
    return subprocess.run(
        [sys.executable, *args],
        env=env,
        cwd=tmp_path,
        stdin=subprocess.DEVNULL,
        capture_output=True,
        text=True,
        timeout=60,
    )


@pytest.mark.parametrize(
    "entry_point",
    [
        # What the `enclave-mcp` console script generated by pip runs.
        ["-c", "import sys; from advanced_vault.mcp_server import main; sys.exit(main())"],
        # What `enclave mcp install` writes into the MCP client config.
        ["-m", "advanced_vault.mcp_server"],
    ],
    ids=["enclave-mcp", "python-m"],
)
def test_entry_points_fail_fast_on_mcp_2(tmp_path, entry_point):
    proc = _run_with_fake_mcp(tmp_path, "2.2.0", *entry_point)

    assert proc.returncode == 1
    assert proc.stdout == ""
    assert "Traceback" not in proc.stderr
    assert len(proc.stderr.strip().splitlines()) == 1
    assert FIX in proc.stderr
    assert not (tmp_path / "vault").exists()  # stopped before building the server


def test_package_import_skips_server_and_mcp_on_mcp_2(tmp_path):
    probe = (
        "import sys, advanced_vault.mcp_server; "
        "print([m for m in ('mcp', 'advanced_vault.mcp_server.server') if m in sys.modules])"
    )
    proc = _run_with_fake_mcp(tmp_path, "2.2.0", "-c", probe)

    assert proc.returncode == 0, proc.stderr
    assert proc.stdout.strip() == "[]"
