"""
Smart Query Router

Classifies user queries and routes them to the appropriate vault layer:
- Layer 1 (Exact): Encrypted KV store for API keys, passwords
- Layer 2 (Fuzzy): DoRA adapters for knowledge, context
- Hybrid: Both layers for comprehensive results

The router uses pattern matching to detect query intent.
"""

import re
from typing import Literal, Optional, List
from dataclasses import dataclass
from enum import Enum


class QueryStrategy(Enum):
    """Query routing strategy."""
    EXACT = "exact"      # Layer 1: KV store (API keys, passwords)
    FUZZY = "fuzzy"      # Layer 2: DoRA inference (knowledge, context)
    HYBRID = "hybrid"    # Both layers combined


@dataclass
class QueryPlan:
    """
    Query execution plan generated by the router.

    Attributes:
        strategy: Which layer(s) to query
        layer: Layer number (1, 2, or [1, 2] for hybrid)
        service: Extracted service name (if applicable)
        confidence: Router confidence (0.0-1.0)
        reasoning: Why this strategy was chosen
    """
    strategy: QueryStrategy
    layer: int | List[int]
    service: Optional[str] = None
    confidence: float = 1.0
    reasoning: str = ""


class SmartRouter:
    """
    Intelligent query router for hybrid vault.

    Uses pattern matching and heuristics to determine query intent
    and route to appropriate storage layer(s).
    """

    # Patterns for exact data queries (Layer 1)
    EXACT_PATTERNS = [
        # Direct requests for credentials
        r"what'?s?\s+(?:is\s+)?(?:my\s+|the\s+)?(.+?)\s+(?:api\s+)?(?:key|token|password|secret|credential)",
        r"show\s+(?:me\s+)?(?:my\s+|the\s+)?(.+?)\s+(?:api\s+)?(?:key|token|password|credential)",
        r"get\s+(?:me\s+)?(?:my\s+|the\s+)?(.+?)\s+(?:api\s+)?(?:key|token|password|secret)",
        r"retrieve\s+(?:my\s+|the\s+)?(.+?)\s+(?:api\s+)?(?:key|token|password|secret)",
        r"give\s+(?:me\s+)?(?:my\s+|the\s+)?(.+?)\s+(?:api\s+)?(?:key|token|password|credential)",
        r"find\s+(?:my\s+|the\s+)?(.+?)\s+(?:api\s+)?(?:key|token|password|secret)",

        # Card and payment details
        r"(?:my\s+|the\s+)?(?:card\s+)?(?:details?|info|information|number)",
        r"(?:credit|debit)\s+card\s+(?:details?|info|information|number)",
        r"card\s+(?:details?|info|information|number)",
        r"payment\s+(?:details?|info|information|method)",
        
        # Generic "details" requests (likely asking for stored data)
        r"(?:my\s+|the\s+)?(.+?)\s+details?",
        r"(?:my\s+|the\s+)?(.+?)\s+info(?:rmation)?",

        # Service-specific requests (simple patterns)
        r"^(.+?)\s+(?:api\s+)?(?:key|token|password|credentials?)$",
        r"credentials?\s+for\s+(.+)",
        r"access\s+(?:token|key)\s+for\s+(.+)",
    ]

    # Patterns for knowledge/context queries (Layer 2)
    FUZZY_PATTERNS = [
        # Why/how questions
        r"why did (?:i|we) (?:choose|pick|select|use) (.+)",
        r"how did (?:i|we) (?:setup|configure|integrate|implement) (.+)",
        r"what was the (?:issue|problem|bug|reason) (?:with|for) (.+)",
        r"when did (?:i|we) (?:decide|implement|change|add) (.+)",
        r"explain (?:my|the|our) (.+?) (?:setup|configuration|integration|decision)",

        # Context requests
        r"tell me about (?:my|the|our) (.+?) (?:setup|integration|decision)",
        r"what do (?:i|we) know about (.+)",
        r"background on (.+)",
        r"context for (.+)",
        r"history of (.+)",

        # Decision reasoning
        r"rationale for (.+)",
        r"pros and cons of (.+)",
        r"comparison (?:of|between) (.+)",
    ]

    # Patterns for combined queries (Hybrid)
    HYBRID_PATTERNS = [
        # Comprehensive information requests (must include "everything", "all", "complete", etc.)
        r"(?:show|give)\s+(?:me\s+)?everything\s+(?:about|for|on)\s+(.+)",
        r"(?:full|complete|all)\s+(?:info|information|details)\s+(?:about|for|on)\s+(.+)",
        r"tell\s+me\s+(?:everything|all)\s+(?:about|for|on)\s+(.+)",
        r"everything\s+(?:about|for|on)\s+(.+)",

        # Multi-aspect questions
        r"(.+?)\s+setup\s+and\s+(?:credentials|keys|passwords)",
        r"(.+?)\s+(?:credentials|keys?)\s+and\s+(?:documentation|notes|context)",
    ]

    # Service name extraction patterns
    SERVICE_KEYWORDS = [
        "stripe", "github", "gitlab", "aws", "gcp", "azure",
        "postgres", "postgresql", "mysql", "mongodb", "redis",
        "slack", "discord", "telegram",
        "openai", "anthropic", "google",
        "vercel", "netlify", "heroku",
        "docker", "kubernetes", "k8s"
    ]

    # Service name aliases (for normalization)
    SERVICE_ALIASES = {
        "postgresql": "postgres",
        "k8s": "kubernetes",
    }

    def __init__(self):
        """Initialize smart router with compiled patterns."""
        self.exact_patterns = [re.compile(p, re.IGNORECASE) for p in self.EXACT_PATTERNS]
        self.fuzzy_patterns = [re.compile(p, re.IGNORECASE) for p in self.FUZZY_PATTERNS]
        self.hybrid_patterns = [re.compile(p, re.IGNORECASE) for p in self.HYBRID_PATTERNS]

        # Compile service keywords pattern
        services = "|".join(self.SERVICE_KEYWORDS)
        self.service_pattern = re.compile(rf"\b({services})\b", re.IGNORECASE)

    def route(self, query: str) -> QueryPlan:
        """
        Route query to appropriate layer(s).

        Args:
            query: User's natural language query

        Returns:
            QueryPlan with routing strategy and metadata
        """
        query = query.strip()

        # Check hybrid patterns first (most specific)
        plan = self._check_hybrid(query)
        if plan:
            return plan

        # Check exact patterns (API keys, passwords)
        plan = self._check_exact(query)
        if plan:
            return plan

        # Check fuzzy patterns (knowledge, context)
        plan = self._check_fuzzy(query)
        if plan:
            return plan

        # Default: fuzzy search (most queries are contextual)
        return QueryPlan(
            strategy=QueryStrategy.FUZZY,
            layer=2,
            service=self._extract_service(query),
            confidence=0.5,
            reasoning="No specific pattern matched, defaulting to fuzzy search"
        )

    def _check_exact(self, query: str) -> Optional[QueryPlan]:
        """Check if query matches exact data patterns."""
        for pattern in self.exact_patterns:
            match = pattern.search(query)
            if match:
                service = match.group(1) if match.lastindex else self._extract_service(query)
                # Normalize service name
                if service:
                    service = service.strip().lower()
                    # Try to extract known service from the captured group
                    known_service = self._extract_service(service)
                    if known_service:
                        service = known_service
                return QueryPlan(
                    strategy=QueryStrategy.EXACT,
                    layer=1,
                    service=service if service else None,
                    confidence=0.9,
                    reasoning=f"Matched exact pattern: requesting credentials/keys"
                )
        return None

    def _check_fuzzy(self, query: str) -> Optional[QueryPlan]:
        """Check if query matches fuzzy/contextual patterns."""
        for pattern in self.fuzzy_patterns:
            match = pattern.search(query)
            if match:
                service = match.group(1) if match.lastindex else self._extract_service(query)
                return QueryPlan(
                    strategy=QueryStrategy.FUZZY,
                    layer=2,
                    service=service.strip() if service else None,
                    confidence=0.85,
                    reasoning=f"Matched fuzzy pattern: requesting context/knowledge"
                )
        return None

    def _check_hybrid(self, query: str) -> Optional[QueryPlan]:
        """Check if query matches hybrid patterns."""
        for pattern in self.hybrid_patterns:
            match = pattern.search(query)
            if match:
                service = match.group(1) if match.lastindex else self._extract_service(query)
                # Normalize service name
                if service:
                    service = service.strip().lower()
                    # Try to extract known service from the captured group
                    known_service = self._extract_service(service)
                    if known_service:
                        service = known_service
                return QueryPlan(
                    strategy=QueryStrategy.HYBRID,
                    layer=[1, 2],
                    service=service if service else None,
                    confidence=0.95,
                    reasoning=f"Matched hybrid pattern: requesting comprehensive information"
                )
        return None

    def _extract_service(self, query: str) -> Optional[str]:
        """
        Extract service name from query.

        Returns:
            Service name if found, None otherwise
        """
        match = self.service_pattern.search(query)
        if match:
            service = match.group(1).lower()
            # Apply alias normalization
            return self.SERVICE_ALIASES.get(service, service)
        return None

    def explain(self, query: str) -> str:
        """
        Explain routing decision for a query.

        Useful for debugging and transparency.

        Args:
            query: User query

        Returns:
            Human-readable explanation
        """
        plan = self.route(query)

        explanation = f"""
Query: "{query}"

Routing Decision:
  Strategy: {plan.strategy.value}
  Layer(s): {plan.layer}
  Service: {plan.service or 'N/A'}
  Confidence: {plan.confidence:.0%}

Reasoning:
  {plan.reasoning}

What this means:
"""

        if plan.strategy == QueryStrategy.EXACT:
            explanation += """  → Will query Layer 1 (Encrypted KV Store)
  → Expects exact data (API key, password, token)
  → No LLM involved, zero hallucination risk
  → Response time: <10ms"""

        elif plan.strategy == QueryStrategy.FUZZY:
            explanation += """  → Will query Layer 2 (DoRA Adapter)
  → Expects contextual/knowledge response
  → LLM inference involved
  → Response time: ~200-300ms"""

        else:  # HYBRID
            explanation += """  → Will query BOTH layers
  → Layer 1: Credentials/exact data
  → Layer 2: Context/knowledge
  → Combined comprehensive response
  → Response time: ~300-400ms"""

        return explanation
