"""Simple GUI localization (EN default, optional PL)."""

from typing import Dict

DEFAULT_LANGUAGE = "en"
SUPPORTED_LANGUAGES: Dict[str, str] = {
    "en": "English",
    "pl": "Polski",
}

STRINGS: Dict[str, Dict[str, str]] = {
    "en": {
        "language.selector.title": "Language",
        "language.selector.description": "Choose app language. English is the default.",
        "language.changed": "Language changed to {language}.",
        "onboarding.title": "Private AI workspace for the agentic web",
        "onboarding.subtitle": "Bring your files, ask privately, and decide what Claude, ChatGPT-like/MCP tools, browsers, and ecommerce agents can see.",
        "onboarding.progress": "Step {completed} of {total}",
        "onboarding.ttfv": "First answer in about 60 seconds",
        "onboarding.continue": "Continue to Dashboard",
        "onboarding.primary": "Add Private Files",
        "onboarding.skip": "Open workspace",
        "onboarding.add_sample": "Open Investor Demo",
        "onboarding.trust.local": "Runs on this Mac",
        "onboarding.trust.account": "Works before cloud setup",
        "onboarding.trust.control": "Exposure stays under your approval",
        "onboarding.step.add.title": "Add private files",
        "onboarding.step.add.description": "Start with a PDF, note, contract, shopping brief, or folder.",
        "onboarding.step.add.cta": "Add Files",
        "onboarding.step.add.value": "Your source material stays local unless you explicitly share it.",
        "onboarding.step.ask.title": "Ask privately",
        "onboarding.step.ask.description": "Open chat and get a grounded answer from the files you just added.",
        "onboarding.step.ask.cta": "Open Private Chat",
        "onboarding.step.ask.value": "Enclave answers from your context instead of handing raw files to a generic assistant.",
        "onboarding.step.protect.title": "Connect apps safely",
        "onboarding.step.protect.description": "Route Claude, ChatGPT-like/MCP tools, agentic browsers, and ecommerce automations through Enclave with approvals and logs.",
        "onboarding.step.protect.cta": "Open Connections",
        "onboarding.step.protect.value": "You keep the upside of agentic tools while controlling information exposure and checkout risk.",
        "onboarding.info.add": "Choose files to start your private workspace.",
        "onboarding.info.protect": "Connect agentic apps through Enclave so access stays controlled, auditable, and revocable.",
        "onboarding.error.open_step": "Could not open onboarding step",
        "onboarding.error.add_sample": "Could not add sample data",
        "onboarding.fix.add_secret": "Open workspace",
        "onboarding.success.sample": "Investor demo ready with {count} sample files. Ask: What blocks autonomous spending above $75?",
        "local_model.download.title": "Download local model",
        "local_model.download.preparing": "Preparing local model download...",
        "local_model.download.ready": "Local model ready",
        "local_model.download.cta": "Download Model",
        "local_model.download.required": "Download the local model once on this Mac before private Q&A can start.",
        "local_model.download.first_run": "First download can take a few minutes.",
        "local_model.download.keep_query": "Download the local model first. Your message is still in the box.",
        "readiness.title": "Readiness",
        "readiness.all_ready": "All systems ready",
        "readiness.next": "Next: {hint}",
        "readiness.action.ready": "Ready",
        "readiness.step.key.label": "Key",
        "readiness.step.key.hint": "Create encrypted entry",
        "readiness.step.key.fix": "Add first secret",
        "readiness.step.dataset.label": "Dataset",
        "readiness.step.dataset.hint": "Upload one PDF",
        "readiness.step.dataset.fix": "Upload document",
        "readiness.step.adapter.label": "Adapter",
        "readiness.step.adapter.hint": "Train one adapter",
        "readiness.step.adapter.fix": "Open training queue",
        "readiness.step.inference.label": "Inference",
        "readiness.step.inference.hint": "Cloud/local answering",
        "readiness.step.inference.fix": "Configure inference",
        "readiness.step.sync.label": "Sync",
        "readiness.step.sync.hint": "Cloud sync online",
        "readiness.step.sync.fix": "Open setup",
        "readiness.error.fix": "Could not apply readiness fix",
        "readiness.fix.open_setup": "Open Setup",
        "inference.cloud": "Cloud inference: Better quality, uses secure cloud",
        "inference.local": "Local inference: Private, works offline",
        "common.ok": "OK",
        "sidebar.home": "Home",
        "sidebar.secrets": "Secrets",
        "sidebar.knowledge": "Knowledge",
        "sidebar.library": "Library",
        "sidebar.training": "Training",
        "sidebar.activity": "Activity",
        "sidebar.permissions": "Permissions",
        "sidebar.statistics": "Statistics",
        "sidebar.langchain": "LangChain",
        "sidebar.setup": "Setup",
        "sidebar.vault": "Vault",
        "sidebar.my_data": "My Data",
        "sidebar.agent": "Agent",
        "sidebar.settings": "Settings",
        "auth.subtitle": "Secure Encrypted Vault with AI Inference",
        "auth.divider.or": "or",
        "auth.email.label": "Email",
        "auth.email.hint": "your@email.com",
        "auth.password.label": "Password",
        "auth.password.hint": "Enter your password",
        "auth.full_name.label": "Full Name (optional)",
        "auth.full_name.hint": "John Doe",
        "auth.submit.signin": "Sign In",
        "auth.submit.signup": "Sign Up",
        "auth.toggle.to_signup": "Don't have an account? Sign up",
        "auth.toggle.to_signin": "Already have an account? Sign in",
        "auth.oauth.google": "Continue with Google",
        "auth.oauth.github": "Continue with GitHub",
        "auth.error.missing_credentials": "Please enter email and password",
        "auth.error.failed": "Authentication failed",
        "auth.error.generic": "Error: {error}",
        "auth.error.oauth": "OAuth error: {error}",
        "landing.tagline": " — Your data. Your agent. Your rules.",
        "ui.settings": "Settings",
        "ui.refresh": "Refresh",
        "ui.add_entry.tooltip": "Add Entry",
        "ui.add_secret": "Add Secret",
        "ui.upload_pdf_knowledge": "Upload PDF (Knowledge)",
        "ui.new_folder": "New Folder",
        "ui.logout": "Logout",
        "ui.search_secrets": "Search secrets...",
        "ui.filter.all": "All",
        "ui.chat_with_ai": "Chat with AI",
        "settings.title": "Settings",
        "settings.vault_info.title": "Vault Information",
        "settings.vault_info.path": "Vault Path: {path}",
        "settings.vault_info.master_key": "Master Key: {path}",
        "settings.vault_info.database": "Database: {path}",
        "settings.encryption.algorithm": "Encryption: XChaCha20-Poly1305",
        "settings.encryption.key_size": "Key Size: 32 bytes (256-bit)",
        "settings.components.title": "Component Status",
        "settings.components.subtitle": "Status of Enclave components and services",
        "settings.components.ocr.name": "AI Knowledge Extraction",
        "settings.components.ocr.description": "Extracts text from scanned documents",
        "settings.components.qa.name": "Q&A Generation",
        "settings.components.qa.description": "Generates Q&A pairs from documents using optimized AI models",
        "settings.components.vault.name": "Secure Vault",
        "settings.components.vault.description": "Encrypted local storage",
        "settings.components.sync.name": "Cloud Sync",
        "settings.components.sync.description": "Secure cloud backup",
        "settings.components.training.name": "AI Training",
        "settings.components.training.description": "Personal AI model training",
        "settings.status.ready": "Ready",
        "settings.status.checking": "Checking...",
        "settings.status.error": "Error",
        "settings.status.unknown": "Unknown",
        "settings.status.ready.optimized_ai": "Ready (Optimized AI)",
        "settings.status.ready.local_ai": "Ready (Local AI)",
        "settings.status.ready.mlx": "Ready (MLX Qwen2.5-3B)",
        "settings.status.ready.ollama": "Ready (Ollama TinyLlama)",
        "settings.status.setup_required_ai": "Setup required (download AI model)",
        "settings.status.qa_model_missing": "Q&A model not downloaded",
        "settings.status.downloading.optimized_ai": "Downloading optimized AI model...",
        "settings.status.downloading.tinyllama": "Downloading TinyLlama...",
        "settings.mcp.title": "MCP Server Integration",
        "settings.mcp.subtitle": "Connect your vault to Claude Desktop or ChatGPT",
        "settings.mcp.status.configured": "Configured",
        "settings.mcp.status.not_configured": "Not Configured",
        "settings.mcp.claude_status": "Claude Desktop: {status}",
        "settings.mcp.claude_not_detected": "Claude Desktop: Not Detected",
        "settings.mcp.test_result": "MCP Server: {message}",
        "settings.mcp.copied": "Config copied to clipboard. Paste into Claude Desktop config file.",
        "settings.mcp.copy_config": "Copy Config to Clipboard",
        "settings.mcp.auto_configure.button": "Auto-Configure Claude Desktop",
        "settings.mcp.auto_configure.success": "MCP server configured. Restart Claude Desktop to activate.",
        "settings.mcp.auto_configure.failed": "Failed to write config. Check permissions.",
        "settings.mcp.auto_configure.error": "Error: {error}",
        "settings.mcp.test.button": "Test Connection",
        "settings.mcp.instructions.title": "Setup Instructions",
        "settings.mcp.instructions.step1": "1. Config file location:\n   {path}",
        "settings.mcp.instructions.step2": "2. Click 'Auto-Configure' to set it up (or 'Copy Config' to paste manually)",
        "settings.mcp.instructions.step3": "3. IMPORTANT: Completely quit and restart Claude Desktop",
        "settings.mcp.instructions.step4": "4. After restart, look for 'Enclave' in your Connectors/Extensions list",
        "settings.mcp.instructions.step5": "5. Test by asking Claude: 'What tools do you have access to?'",
        "settings.inference.title": "Cloud Inference (Opt-in)",
        "settings.inference.subtitle": "Use cloud models for higher quality responses. Data is encrypted before transmission.",
        "settings.inference.enable": "Enable Cloud Inference",
        "settings.inference.bullet1": "Data encrypted with ChaCha20-Poly1305 before transmission",
        "settings.inference.bullet2": "Cloud server never sees plaintext data",
        "settings.inference.bullet3": "Processed data deleted immediately after response",
        "settings.permissions.title": "Agent Permissions",
        "settings.permissions.subtitle": "Manage which AI agents can access your data",
        "settings.permissions.button": "Manage Permissions",
        "settings.qa_setup.dialog_title": "Setting up Q&A Generation",
        "settings.qa_setup.preparing": "Preparing Q&A Generation...",
        "settings.qa_setup.ready": "Q&A Generation ready",
        "settings.qa_setup.tooltip.setup": "Setup Q&A Generation",
        "settings.qa_setup.tooltip.download_optimized": "Download optimized AI model (~3GB)",
        "settings.qa_setup.tooltip.optimized_ready": "Optimized AI model ready",
        "settings.qa_setup.tooltip.download_tinyllama": "Download TinyLlama model",
        "settings.ocr_setup.dialog_title": "Setting up AI Knowledge Extraction",
        "settings.ocr_setup.preparing": "Preparing OCR...",
        "settings.setup.time_remaining": "{time} remaining",
    },
    "pl": {
        "language.selector.title": "Język",
        "language.selector.description": "Wybierz język aplikacji. Domyślnie: angielski.",
        "language.changed": "Zmieniono język na: {language}.",
        "onboarding.title": "Zacznij w 3 prostych krokach",
        "onboarding.subtitle": "Dodaj plik, zadaj pytanie i zachowaj kontrolę nad tym, co AI może odczytać lub wydać.",
        "onboarding.progress": "Krok {completed} z {total}",
        "onboarding.ttfv": "Pierwsza odpowiedź w około 60 sekund",
        "onboarding.continue": "Przejdź do dashboardu",
        "onboarding.primary": "Dodaj pierwszy plik",
        "onboarding.skip": "Pomiń na razie",
        "onboarding.add_sample": "Uruchom demo workspace",
        "onboarding.trust.local": "Lokalnie na tym Macu",
        "onboarding.trust.account": "Bez zakładania konta",
        "onboarding.trust.control": "Ty zatwierdzasz wrażliwe akcje",
        "onboarding.step.add.title": "1. Dodaj plik",
        "onboarding.step.add.description": "Zacznij od PDF-a, notatki, umowy albo folderu.",
        "onboarding.step.add.cta": "Dodaj pliki",
        "onboarding.step.add.value": "Nic nie opuszcza tego urządzenia bez Twojej decyzji.",
        "onboarding.step.ask.title": "2. Zadaj pytanie",
        "onboarding.step.ask.description": "Otwórz chat i zapytaj o to, co właśnie dodałeś.",
        "onboarding.step.ask.cta": "Otwórz chat",
        "onboarding.step.ask.value": "Odpowiedzi pochodzą z Twoich plików, nie z ogólnego bota.",
        "onboarding.step.protect.title": "3. Włącz guardrails",
        "onboarding.step.protect.description": "Sprawdź kontrolę dostępu, kill switch i limity płatności.",
        "onboarding.step.protect.cta": "Sprawdź ochronę",
        "onboarding.step.protect.value": "Ty kontrolujesz wrażliwe odczyty i wydatki.",
        "onboarding.info.add": "Wybierz pliki, aby uruchomić prywatny workspace.",
        "onboarding.info.protect": "Sprawdź reguły, lease'y i guardrails płatności.",
        "onboarding.error.open_step": "Nie udało się otworzyć kroku onboardingu",
        "onboarding.error.add_sample": "Nie udało się dodać danych przykładowych",
        "onboarding.fix.add_secret": "Otwórz workspace",
        "onboarding.success.sample": "Demo workspace gotowy z {count} przykładowymi plikami. Zapytaj: co blokuje autonomiczne wydatki powyżej 75 dolarów?",
        "local_model.download.title": "Pobierz model lokalny",
        "local_model.download.preparing": "Przygotowywanie pobierania modelu lokalnego...",
        "local_model.download.ready": "Model lokalny gotowy",
        "local_model.download.cta": "Pobierz model",
        "local_model.download.required": "Pobierz model lokalny raz na tym Macu, aby uruchomić prywatne Q&A.",
        "local_model.download.first_run": "Pierwsze pobranie może potrwać kilka minut.",
        "local_model.download.keep_query": "Najpierw pobierz model lokalny. Twoja wiadomość pozostała w polu.",
        "readiness.title": "Gotowość",
        "readiness.all_ready": "Wszystkie systemy gotowe",
        "readiness.next": "Następny krok: {hint}",
        "readiness.action.ready": "Gotowe",
        "readiness.step.key.label": "Klucz",
        "readiness.step.key.hint": "Utwórz zaszyfrowany wpis",
        "readiness.step.key.fix": "Dodaj pierwszy sekret",
        "readiness.step.dataset.label": "Zbiór danych",
        "readiness.step.dataset.hint": "Wgraj jeden PDF",
        "readiness.step.dataset.fix": "Wgraj dokument",
        "readiness.step.adapter.label": "Adapter",
        "readiness.step.adapter.hint": "Wytrenuj jeden adapter",
        "readiness.step.adapter.fix": "Otwórz kolejkę treningu",
        "readiness.step.inference.label": "Inferencja",
        "readiness.step.inference.hint": "Odpowiedzi cloud/local",
        "readiness.step.inference.fix": "Skonfiguruj inferencję",
        "readiness.step.sync.label": "Synchronizacja",
        "readiness.step.sync.hint": "Cloud sync online",
        "readiness.step.sync.fix": "Otwórz setup",
        "readiness.error.fix": "Nie udało się naprawić kroku gotowości",
        "readiness.fix.open_setup": "Otwórz setup",
        "inference.cloud": "Cloud inference: lepsza jakość, bezpieczna chmura",
        "inference.local": "Local inference: prywatnie, działa offline",
        "common.ok": "OK",
        "sidebar.home": "Strona główna",
        "sidebar.secrets": "Sekrety",
        "sidebar.knowledge": "Wiedza",
        "sidebar.library": "Biblioteka",
        "sidebar.training": "Trening",
        "sidebar.activity": "Aktywność",
        "sidebar.permissions": "Uprawnienia",
        "sidebar.statistics": "Statystyki",
        "sidebar.langchain": "LangChain",
        "sidebar.setup": "Konfiguracja",
        "sidebar.vault": "Vault",
        "sidebar.my_data": "Moje dane",
        "sidebar.agent": "Agent",
        "sidebar.settings": "Ustawienia",
        "auth.subtitle": "Bezpieczny zaszyfrowany vault z inferencją AI",
        "auth.divider.or": "lub",
        "auth.email.label": "Email",
        "auth.email.hint": "twoj@email.com",
        "auth.password.label": "Hasło",
        "auth.password.hint": "Wpisz hasło",
        "auth.full_name.label": "Imię i nazwisko (opcjonalnie)",
        "auth.full_name.hint": "Jan Kowalski",
        "auth.submit.signin": "Zaloguj się",
        "auth.submit.signup": "Załóż konto",
        "auth.toggle.to_signup": "Nie masz konta? Zarejestruj się",
        "auth.toggle.to_signin": "Masz już konto? Zaloguj się",
        "auth.oauth.google": "Kontynuuj z Google",
        "auth.oauth.github": "Kontynuuj z GitHub",
        "auth.error.missing_credentials": "Podaj email i hasło",
        "auth.error.failed": "Uwierzytelnianie nie powiodło się",
        "auth.error.generic": "Błąd: {error}",
        "auth.error.oauth": "Błąd OAuth: {error}",
        "landing.tagline": " — Twoje dane. Twój agent. Twoje zasady.",
        "ui.settings": "Ustawienia",
        "ui.refresh": "Odśwież",
        "ui.add_entry.tooltip": "Dodaj wpis",
        "ui.add_secret": "Dodaj sekret",
        "ui.upload_pdf_knowledge": "Wgraj PDF (Wiedza)",
        "ui.new_folder": "Nowy folder",
        "ui.logout": "Wyloguj",
        "ui.search_secrets": "Szukaj sekretów...",
        "ui.filter.all": "Wszystkie",
        "ui.chat_with_ai": "Czat z AI",
        "settings.title": "Ustawienia",
        "settings.vault_info.title": "Informacje o vault",
        "settings.vault_info.path": "Ścieżka vault: {path}",
        "settings.vault_info.master_key": "Klucz główny: {path}",
        "settings.vault_info.database": "Baza danych: {path}",
        "settings.encryption.algorithm": "Szyfrowanie: XChaCha20-Poly1305",
        "settings.encryption.key_size": "Rozmiar klucza: 32 bajty (256-bit)",
        "settings.components.title": "Status komponentów",
        "settings.components.subtitle": "Stan komponentów i usług Enclave",
        "settings.components.ocr.name": "Ekstrakcja wiedzy AI",
        "settings.components.ocr.description": "Wyodrębnia tekst ze skanowanych dokumentów",
        "settings.components.qa.name": "Generowanie Q&A",
        "settings.components.qa.description": "Tworzy pary pytań i odpowiedzi z dokumentów",
        "settings.components.vault.name": "Bezpieczny vault",
        "settings.components.vault.description": "Lokalny zaszyfrowany storage",
        "settings.components.sync.name": "Synchronizacja chmurowa",
        "settings.components.sync.description": "Bezpieczna kopia w chmurze",
        "settings.components.training.name": "Trening AI",
        "settings.components.training.description": "Trening własnego modelu AI",
        "settings.status.ready": "Gotowe",
        "settings.status.checking": "Sprawdzanie...",
        "settings.status.error": "Błąd",
        "settings.status.unknown": "Nieznany",
        "settings.status.ready.optimized_ai": "Gotowe (zoptymalizowane AI)",
        "settings.status.ready.local_ai": "Gotowe (lokalne AI)",
        "settings.status.ready.mlx": "Gotowe (MLX Qwen2.5-3B)",
        "settings.status.ready.ollama": "Gotowe (Ollama TinyLlama)",
        "settings.status.setup_required_ai": "Wymagany setup (pobierz model AI)",
        "settings.status.qa_model_missing": "Model Q&A nie został pobrany",
        "settings.status.downloading.optimized_ai": "Pobieranie zoptymalizowanego modelu AI...",
        "settings.status.downloading.tinyllama": "Pobieranie TinyLlama...",
        "settings.mcp.title": "Integracja serwera MCP",
        "settings.mcp.subtitle": "Połącz vault z Claude Desktop lub ChatGPT",
        "settings.mcp.status.configured": "Skonfigurowano",
        "settings.mcp.status.not_configured": "Nie skonfigurowano",
        "settings.mcp.claude_status": "Claude Desktop: {status}",
        "settings.mcp.claude_not_detected": "Claude Desktop: Nie wykryto",
        "settings.mcp.test_result": "Serwer MCP: {message}",
        "settings.mcp.copied": "Skopiowano konfigurację do schowka. Wklej ją do pliku konfiguracyjnego Claude Desktop.",
        "settings.mcp.copy_config": "Kopiuj konfigurację",
        "settings.mcp.auto_configure.button": "Auto-konfiguruj Claude Desktop",
        "settings.mcp.auto_configure.success": "Skonfigurowano serwer MCP. Uruchom ponownie Claude Desktop.",
        "settings.mcp.auto_configure.failed": "Nie udało się zapisać konfiguracji. Sprawdź uprawnienia.",
        "settings.mcp.auto_configure.error": "Błąd: {error}",
        "settings.mcp.test.button": "Test połączenia",
        "settings.mcp.instructions.title": "Instrukcja konfiguracji",
        "settings.mcp.instructions.step1": "1. Lokalizacja pliku konfiguracyjnego:\n   {path}",
        "settings.mcp.instructions.step2": "2. Kliknij 'Auto-konfiguruj' (lub 'Kopiuj konfigurację' i wklej ręcznie)",
        "settings.mcp.instructions.step3": "3. WAŻNE: całkowicie zamknij i uruchom ponownie Claude Desktop",
        "settings.mcp.instructions.step4": "4. Po restarcie szukaj 'Enclave' na liście Connectors/Extensions",
        "settings.mcp.instructions.step5": "5. Przetestuj pytaniem: 'What tools do you have access to?'",
        "settings.inference.title": "Inferencja chmurowa (opcjonalna)",
        "settings.inference.subtitle": "Użyj modeli chmurowych dla wyższej jakości odpowiedzi. Dane są szyfrowane przed wysłaniem.",
        "settings.inference.enable": "Włącz inferencję chmurową",
        "settings.inference.bullet1": "Dane szyfrowane ChaCha20-Poly1305 przed wysłaniem",
        "settings.inference.bullet2": "Serwer chmurowy nie widzi danych jawnych",
        "settings.inference.bullet3": "Przetworzone dane są usuwane po odpowiedzi",
        "settings.permissions.title": "Uprawnienia agentów",
        "settings.permissions.subtitle": "Zarządzaj dostępem agentów AI do danych",
        "settings.permissions.button": "Zarządzaj uprawnieniami",
        "settings.qa_setup.dialog_title": "Konfigurowanie generowania Q&A",
        "settings.qa_setup.preparing": "Przygotowanie generowania Q&A...",
        "settings.qa_setup.ready": "Generowanie Q&A gotowe",
        "settings.qa_setup.tooltip.setup": "Skonfiguruj generowanie Q&A",
        "settings.qa_setup.tooltip.download_optimized": "Pobierz zoptymalizowany model AI (~3GB)",
        "settings.qa_setup.tooltip.optimized_ready": "Zoptymalizowany model AI gotowy",
        "settings.qa_setup.tooltip.download_tinyllama": "Pobierz model TinyLlama",
        "settings.ocr_setup.dialog_title": "Konfigurowanie ekstrakcji wiedzy AI",
        "settings.ocr_setup.preparing": "Przygotowanie OCR...",
        "settings.setup.time_remaining": "Pozostało: {time}",
    },
}


def get_text(language: str, key: str, **kwargs) -> str:
    """Get localized string with English fallback."""
    lang = language if language in SUPPORTED_LANGUAGES else DEFAULT_LANGUAGE
    value = STRINGS.get(lang, {}).get(key) or STRINGS[DEFAULT_LANGUAGE].get(key) or key
    if kwargs:
        try:
            return value.format(**kwargs)
        except Exception:
            return value
    return value
